import type { Job, Insight, CVTailor, IndustryCompany } from "@/lib/types";

// ─── Mock jobs ───────────────────────────────────────────────────────────────

export const MOCK_JOBS: Job[] = [
  {
    id: "mock_j001",
    title: "Senior Product Manager, Growth",
    company: "Notion Labs",
    ticker: null,
    country: "US",
    city: "San Francisco",
    remote: "hybrid",
    type: "Full-time",
    salaryMin: 180_000,
    salaryMax: 230_000,
    ccy: "USD",
    yearsMin: 5,
    yearsMax: 8,
    industry: "tech.saas",
    skills: ["Roadmap", "Growth", "Analytics", "SQL"],
    description:
      "Drive growth funnel for self-serve SaaS. Partner with eng & marketing on activation experiments. Own north-star metrics for SMB self-serve conversion.\n\nRequirements:\n- 5+ years PM experience at SaaS companies\n- Strong data analytics skills (SQL, Looker)\n- Experience running A/B experiments at scale\n- Excellent cross-functional collaboration",
    source: "greenhouse",
    sourceUrl: "https://boards.greenhouse.io/notion/jobs/example-12345",
    postedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.91,
    matchReasons: ["Growth × Senior PM 對齊", "SaaS 經驗 5+ yr", "Roadmap 經驗"],
  },
  {
    id: "mock_j002",
    title: "Product Manager, Platform",
    company: "Stripe",
    ticker: null,
    country: "JP",
    city: "Tokyo",
    remote: "onsite",
    type: "Full-time",
    salaryMin: 16_000_000,
    salaryMax: 22_000_000,
    ccy: "JPY",
    yearsMin: 4,
    yearsMax: 7,
    industry: "fintech",
    skills: ["Platform", "API", "Stakeholder mgmt"],
    description:
      "Own Stripe APIs roadmap for Japan market. Work closely with local engineering and business teams to define and ship platform capabilities.\n\nRequirements:\n- 4+ years product management experience\n- Strong understanding of APIs and developer ecosystems\n- Japanese business level proficiency preferred\n- Experience in fintech or payments domain",
    source: "lever",
    sourceUrl: "https://jobs.lever.co/stripe/example-pm-platform",
    postedAt: new Date(Date.now() - 5 * 3_600_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.86,
    matchReasons: ["Stakeholder × API 經驗", "東京 location 偏好"],
  },
  {
    id: "mock_j003",
    title: "Senior PM, AI Copilot",
    company: "GitHub",
    ticker: "MSFT",
    country: "US",
    city: "Remote",
    remote: "remote",
    type: "Full-time",
    salaryMin: 195_000,
    salaryMax: 245_000,
    ccy: "USD",
    yearsMin: 6,
    yearsMax: 10,
    industry: "ai",
    skills: ["AI", "Developer", "Roadmap", "Analytics"],
    description:
      "Define and ship Copilot Workspace for developers. Lead product strategy for AI-powered developer tools reaching 100M+ developers globally.\n\nRequirements:\n- 6+ years PM experience\n- Experience with AI/ML products\n- Strong technical background (engineering background preferred)\n- Track record of shipping developer-focused products",
    source: "linkedin",
    sourceUrl: "https://www.linkedin.com/jobs/view/example-3892",
    postedAt: new Date(Date.now() - 1 * 86_400_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.84,
    matchReasons: ["AI 產品經驗", "Remote 偏好"],
  },
  {
    id: "mock_j004",
    title: "Product Manager, Consumer Growth",
    company: "Shopee",
    ticker: "SE",
    country: "TW",
    city: "Taipei",
    remote: "hybrid",
    type: "Full-time",
    salaryMin: 1_800_000,
    salaryMax: 2_800_000,
    ccy: "TWD",
    yearsMin: 4,
    yearsMax: 7,
    industry: "retail",
    skills: ["Growth", "A/B Testing", "Mobile"],
    description:
      "Drive consumer activation for SE Asia marketplace. Responsible for user acquisition, retention and LTV growth for Taiwan market.\n\nRequirements:\n- 4+ years growth PM experience\n- Strong A/B testing and experimentation skills\n- Mobile product experience\n- Data-driven decision making",
    source: "104",
    sourceUrl: "https://www.104.com.tw/job/example-shopee",
    postedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.79,
    matchReasons: ["Growth × A/B 對齊", "Taipei 在地"],
  },
  {
    id: "mock_j005",
    title: "Lead Product Manager, B2B SaaS",
    company: "Atlassian",
    ticker: "TEAM",
    country: "AU",
    city: "Sydney",
    remote: "hybrid",
    type: "Full-time",
    salaryMin: 230_000,
    salaryMax: 290_000,
    ccy: "AUD",
    yearsMin: 7,
    yearsMax: 12,
    industry: "tech.saas",
    skills: ["Roadmap", "Stakeholder", "Enterprise"],
    description:
      "Lead Jira Service Management PM team. Own the product vision and strategy for ITSM products serving enterprise customers worldwide.\n\nRequirements:\n- 7+ years PM experience, 2+ years leading PM teams\n- Enterprise SaaS product experience\n- Strong stakeholder management skills\n- Experience with ITSM or workflow tools a plus",
    source: "lever",
    sourceUrl: "https://www.atlassian.com/company/careers/example-lead-pm",
    postedAt: new Date(Date.now() - 6 * 3_600_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.74,
    matchReasons: ["B2B SaaS Senior PM"],
  },
  {
    id: "mock_j006",
    title: "Product Manager, Health Records",
    company: "Cake Health",
    ticker: null,
    country: "TW",
    city: "Taipei",
    remote: "remote",
    type: "Contract",
    salaryMin: 1_500_000,
    salaryMax: 2_000_000,
    ccy: "TWD",
    yearsMin: 3,
    yearsMax: 6,
    industry: "health",
    skills: ["FHIR", "Compliance", "Mobile"],
    description:
      "Build patient-facing health record app. Define product requirements for FHIR-compliant health data platform connecting patients and providers.\n\nRequirements:\n- 3+ years product management experience\n- Healthcare domain knowledge\n- Understanding of health data standards (FHIR, HL7)\n- Mobile product experience",
    source: "cake",
    sourceUrl: "https://www.cakeresume.com/jobs/example-cakehealth",
    postedAt: new Date(Date.now() - 12 * 3_600_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.71,
    matchReasons: ["Mobile 經驗"],
  },
  {
    id: "mock_j007",
    title: "Senior PM, Payments",
    company: "Wise",
    ticker: "WISE.L",
    country: "GB",
    city: "London",
    remote: "hybrid",
    type: "Full-time",
    salaryMin: 95_000,
    salaryMax: 130_000,
    ccy: "GBP",
    yearsMin: 5,
    yearsMax: 9,
    industry: "fintech",
    skills: ["Payments", "Compliance", "API"],
    description:
      "Own cross-border payments roadmap. Define and execute product strategy for international money transfer products serving millions of customers.\n\nRequirements:\n- 5+ years PM experience in fintech or payments\n- Knowledge of payment rails and compliance requirements\n- API product experience\n- Strong analytical skills",
    source: "greenhouse",
    sourceUrl: "https://wise.jobs/example-senior-pm-payments",
    postedAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.69,
    matchReasons: ["Senior 年資"],
  },
  {
    id: "mock_j008",
    title: "Product Manager, Consumer AI",
    company: "Perplexity",
    ticker: null,
    country: "US",
    city: "San Francisco",
    remote: "onsite",
    type: "Full-time",
    salaryMin: 200_000,
    salaryMax: 260_000,
    ccy: "USD",
    yearsMin: 4,
    yearsMax: 8,
    industry: "ai",
    skills: ["AI", "Search", "Mobile"],
    description:
      "Lead consumer answers experience. Define the next generation of AI-powered search and knowledge products for millions of daily users.\n\nRequirements:\n- 4+ years PM experience\n- Experience with AI/ML consumer products\n- Strong mobile product background\n- Passion for search and knowledge products",
    source: "company",
    sourceUrl: "https://www.perplexity.ai/careers/example-pm-consumer",
    postedAt: new Date(Date.now() - 8 * 3_600_000).toISOString(),
    crawledAt: new Date().toISOString(),
    score: 0.66,
    matchReasons: ["AI × Mobile"],
  },
];

// ─── Mock insights ────────────────────────────────────────────────────────────

export function getMockInsight(jobId: string, jobTitle: string, company: string): Insight {
  return {
    swot: {
      S: [
        "5 年以上 PM 經驗，與職缺要求高度匹配",
        "具備 A/B 測試與成長型產品實戰經驗",
        "SQL × 數據分析能力符合職缺偏好",
      ],
      W: [
        `尚未有 ${company} 所在產業的直接經驗`,
        "主要工作地點在台灣，需強化跨時區協作說明",
      ],
      O: [
        `${company} 正處於快速成長期，能提供 career acceleration`,
        "職缺技能與履歷強項高度重疊，面試通過率較高",
      ],
      T: [
        "競爭激烈，建議爭取內部推薦管道",
        "需確認工作授權/簽證狀態",
      ],
    },
    risks: [
      { label: "工作授權", severity: "high", note: "請確認是否需要工作簽證或 sponsorship。" },
      { label: "競爭程度", severity: "med", note: `${jobTitle} 平均收到 100–300+ 份申請，建議透過 referral 投遞。` },
    ],
    strategy:
      `針對 ${company} 面試：(1) 用 STAR 格式準備 2–3 個 growth metric 改善案例；(2) 研究 ${company} 近期產品更新與競品對比；(3) 準備「為什麼選擇 ${company}」的具體論述，聚焦產品 mission 契合度。`,
    questions: [
      {
        q: `How would you define success metrics for ${company}'s core product?`,
        outline: "從用戶價值 → 業務指標 → leading/lagging indicators 層層建立 metric framework。",
      },
      {
        q: "Describe a time you drove significant growth. What was your approach?",
        outline: "Situation → experiment design → hypothesis → results → learnings。強調數據驅動決策。",
      },
      {
        q: "How do you prioritize when engineering resources are limited?",
        outline: "RICE / ICE scoring + strategic alignment + stakeholder communication。展示判斷力。",
      },
    ],
    refs: [
      {
        title: `${company} Product Interview Experience`,
        source: "Glassdoor",
        url: "https://www.glassdoor.com/Interview/",
      },
      {
        title: "Senior PM Interview Preparation Guide",
        source: "Lenny's Newsletter",
        url: "https://www.lennysnewsletter.com/",
      },
    ],
  };
}

// ─── Mock CV tailor ───────────────────────────────────────────────────────────

export function getMockCV(jobTitle: string, company: string): CVTailor {
  return {
    summary: {
      before: "Senior Product Manager with experience in B2B SaaS and mobile products.",
      after: `Senior Product Manager (6 yr) specializing in growth and data-driven product development — drove activation +38% across multiple PLG products. Seeking to bring growth expertise to ${company}'s ${jobTitle} role.`,
    },
    bullets: [
      {
        before: "Led product roadmap for SaaS dashboard.",
        after: "Owned growth roadmap for B2B SaaS dashboard; ran 24 A/B tests in 12 months, lifting activation 38% and reducing time-to-value by 40%.",
      },
      {
        before: "Worked with engineering and marketing teams.",
        after: `Aligned eng / marketing / data on north-star metric; restructured weekly review to reduce roadmap churn 20% — directly applicable to ${company}'s cross-functional culture.`,
      },
      {
        before: "Used SQL to analyze user behavior.",
        after: "Self-serve SQL × Looker on warehouse; built self-serve PM analytics handbook adopted org-wide, enabling 10x faster experiment analysis.",
      },
    ],
    diffNote: "所有改寫均基於原履歷既有事實，僅重新框架、量化並對齊職缺需求。請確認數字與事實正確後再使用。",
  };
}

// ─── Industry Top 100 mock ────────────────────────────────────────────────────

export const INDUSTRY_TOP100: Record<string, IndustryCompany[]> = {
  "tech.saas": [
    { rank: 1, name: "Microsoft", ticker: "MSFT", price: 432.10, d1: 0.011, m1: 0.063, y1: 0.21,
      pros: ["穩定 / 福利優", "WLB 中等", "內部移動容易"], cons: ["大公司流程慢", "升遷慢"],
      profile: "綜合 SaaS + 雲 + AI Copilot 旗艦", trend: "AI Copilot 商業化加速，Azure 持續成長",
      sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/Overview/Working-at-Microsoft" }, { name: "10-K", url: "https://www.microsoft.com/investor" }] },
    { rank: 2, name: "Salesforce", ticker: "CRM", price: 271.55, d1: -0.004, m1: 0.022, y1: 0.09,
      pros: ["Trailhead 學習文化", "國際機會多"], cons: ["年度評估壓力大", "RTO 政策爭議"],
      profile: "CRM + Data Cloud + AI Agentforce", trend: "Agentforce 帶動 attach，但成熟期競爭加劇",
      sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/Overview/Working-at-Salesforce" }] },
    { rank: 3, name: "Atlassian", ticker: "TEAM", price: 210.30, d1: 0.018, m1: 0.041, y1: 0.18,
      pros: ["遠距文化成熟", "明確 OKR"], cons: ["澳洲 vs 美國時差", "新鮮人路徑少"],
      profile: "Jira / Confluence / Loom", trend: "Cloud 遷移已過半，Rovo AI 為下一動能",
      sources: [{ name: "Atlassian Blog", url: "https://www.atlassian.com/blog" }] },
    { rank: 4, name: "ServiceNow", ticker: "NOW", price: 988.20, d1: 0.007, m1: 0.038, y1: 0.27,
      pros: ["企業客戶穩", "薪酬競爭力高"], cons: ["產品線複雜", "內部政治"],
      profile: "Workflow 平台龍頭", trend: "AI agent 整合 + 政府市場擴張",
      sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/Overview/Working-at-ServiceNow" }] },
    { rank: 5, name: "Notion Labs", ticker: "—", price: null, d1: null, m1: null, y1: null,
      pros: ["設計文化強", "產品 craft 高"], cons: ["fast pace", "SF 為主"],
      profile: "Workspace × AI", trend: "Q&A / Agent 推動 ARPU 成長",
      sources: [{ name: "Notion Careers", url: "https://www.notion.so/careers" }] },
    { rank: 6, name: "HubSpot", ticker: "HUBS", price: 605.10, d1: 0.005, m1: 0.013, y1: 0.10,
      pros: ["WLB 良好", "社群文化"], cons: ["漲薪 cap", "產品線割裂"],
      profile: "SMB CRM × Marketing", trend: "AI 助理 Breeze 補強 stack",
      sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/Overview/Working-at-HubSpot" }] },
  ],
  "ai": [
    { rank: 1, name: "OpenAI", ticker: "—", price: null, d1: null, m1: null, y1: null,
      pros: ["前沿研究", "資源充沛"], cons: ["人事波動大", "壓力高"],
      profile: "通用 AI 旗艦 (GPT / o3)", trend: "GPT-5 推進 enterprise + agent 能力",
      sources: [{ name: "OpenAI Careers", url: "https://openai.com/careers" }] },
    { rank: 2, name: "Anthropic", ticker: "—", price: null, d1: null, m1: null, y1: null,
      pros: ["安全研究強", "研究氛圍好"], cons: ["招聘 bar 極高", "產品線少"],
      profile: "Claude × 安全 AI", trend: "Enterprise 客戶快速成長",
      sources: [{ name: "Anthropic Careers", url: "https://www.anthropic.com/careers" }] },
    { rank: 3, name: "Nvidia", ticker: "NVDA", price: 1080, d1: 0.022, m1: 0.18, y1: 0.92,
      pros: ["薪酬頂級", "CUDA 護城河"], cons: ["強度高", "硬體週期風險"],
      profile: "AI 算力 + 軟體生態", trend: "Blackwell 推進 + 自有 cloud",
      sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/Overview/Working-at-NVIDIA" }] },
    { rank: 4, name: "Perplexity", ticker: "—", price: null, d1: null, m1: null, y1: null,
      pros: ["快速迭代", "產品 craft"], cons: ["商業模式仍試錯", "資金壓力"],
      profile: "搜尋 × 答覆 AI", trend: "進攻 enterprise search",
      sources: [{ name: "Perplexity Careers", url: "https://www.perplexity.ai/careers" }] },
  ],
  "fintech": [
    { rank: 1, name: "Visa", ticker: "V", price: 285.20, d1: 0.003, m1: 0.018, y1: 0.12,
      pros: ["穩定", "全球機會多"], cons: ["大公司步調", "創新慢"],
      profile: "卡組織龍頭", trend: "real-time payment + token 業務擴張",
      sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/Overview/Working-at-Visa" }] },
    { rank: 2, name: "Stripe", ticker: "—", price: null, d1: null, m1: null, y1: null,
      pros: ["工程文化頂尖", "國際視野廣"], cons: ["升遷 bar 高", "RTO 趨嚴"],
      profile: "Internet 經濟基礎建設", trend: "AI agent payments + capital 業務",
      sources: [{ name: "Stripe Careers", url: "https://stripe.com/jobs" }] },
    { rank: 3, name: "Wise", ticker: "WISE.L", price: 8.20, d1: 0.005, m1: 0.012, y1: 0.04,
      pros: ["透明文化", "遠距彈性高"], cons: ["薪資較其他金融低", "成長趨緩"],
      profile: "跨境匯款領導品牌", trend: "B2B & 平台合作擴張",
      sources: [{ name: "Wise Careers", url: "https://wise.com/gb/careers/" }] },
  ],
  "tech.consumer": [
    { rank: 1, name: "Apple", ticker: "AAPL", price: 228.87, d1: 0.005, m1: 0.03, y1: 0.15,
      pros: ["品牌聲望", "優質福利"], cons: ["競爭激烈", "保密文化嚴"],
      profile: "消費電子 + 服務生態", trend: "Apple Intelligence AI 功能整合",
      sources: [{ name: "Apple Jobs", url: "https://jobs.apple.com" }] },
    { rank: 2, name: "Meta", ticker: "META", price: 564.10, d1: 0.012, m1: 0.08, y1: 0.65,
      pros: ["薪酬頂級", "AI 資源充沛"], cons: ["文化轉型期", "外部形象壓力"],
      profile: "社群 + AR/VR + AI", trend: "Llama 開源 + Reality Labs 押注",
      sources: [{ name: "Meta Careers", url: "https://www.metacareers.com" }] },
  ],
  "health": [
    { rank: 1, name: "Philips Healthcare", ticker: "PHG", price: 22.50, d1: -0.002, m1: 0.05, y1: 0.08,
      pros: ["穩定", "醫療設備龍頭"], cons: ["轉型緩慢", "法規複雜"],
      profile: "醫療影像 + 患者監護", trend: "AI 輔助診斷 + 遠距醫療擴張",
      sources: [{ name: "Philips Careers", url: "https://www.careers.philips.com" }] },
  ],
  "retail": [
    { rank: 1, name: "Shopee / Sea Ltd", ticker: "SE", price: 68.50, d1: 0.015, m1: 0.12, y1: 0.45,
      pros: ["成長快速", "東南亞市場領先"], cons: ["高強度工作", "政策風險"],
      profile: "SEA 電商 + 金融 + 遊戲", trend: "Shopee Pay + AI 推薦引擎強化",
      sources: [{ name: "Shopee Careers", url: "https://careers.shopee.tw" }] },
    { rank: 2, name: "Momo購物", ticker: "8454.TWO", price: 121.50, d1: 0.003, m1: 0.02, y1: 0.05,
      pros: ["本土最大電商", "穩定"], cons: ["成長趨緩", "競爭壓力大"],
      profile: "台灣 B2C 電商領導品牌", trend: "直播電商 + 物流優化",
      sources: [{ name: "Momo Careers", url: "https://www.momocorp.com.tw/recruit" }] },
  ],
};

// ─── Industry list ────────────────────────────────────────────────────────────

export const INDUSTRIES = [
  { id: "tech.saas", name: "SaaS / B2B Software" },
  { id: "tech.consumer", name: "Consumer Tech" },
  { id: "fintech", name: "Fintech" },
  { id: "ai", name: "AI / Infra" },
  { id: "health", name: "Health Tech" },
  { id: "retail", name: "Retail / E-commerce" },
];

export const JOB_SOURCES = [
  { id: "greenhouse", name: "Greenhouse" },
  { id: "lever", name: "Lever" },
  { id: "linkedin", name: "LinkedIn" },
  { id: "indeed", name: "Indeed" },
  { id: "104", name: "104 人力銀行" },
  { id: "cake", name: "CakeResume" },
  { id: "remotive", name: "Remotive" },
  { id: "adzuna", name: "Adzuna" },
  { id: "company", name: "公司官網" },
];
