// Mock data for AI Hunter prototype
window.AH_DATA = {
  user: {
    name: "Alex Chen",
    email: "alex.chen@example.com",
    headline: "Senior Product Manager · 6 yr",
    avatar: "AC",
    resumeName: "PM_Alex_v3.pdf",
  },
  resume: {
    skills: [
      { name: "Product Roadmap", years: 5 },
      { name: "Growth", years: 4 },
      { name: "SQL / Analytics", years: 4 },
      { name: "Stakeholder mgmt", years: 6 },
      { name: "A/B Testing", years: 3 },
      { name: "Figma", years: 2 },
    ],
    experience: [
      { title: "Senior PM, Growth", company: "Foo SaaS", years: "2023–now", location: "Taipei" },
      { title: "Product Manager", company: "Bar Mobile", years: "2020–2023", location: "Taipei" },
      { title: "Associate PM", company: "Baz", years: "2018–2020", location: "Taipei" },
    ],
    locations: ["Taipei", "Remote", "Tokyo"],
    salaryMin: 2400000,
    languages: ["zh-TW", "en", "ja-JP·N3"],
  },
  sources: [
    { id: "greenhouse", name: "Greenhouse" },
    { id: "lever", name: "Lever" },
    { id: "linkedin", name: "LinkedIn" },
    { id: "indeed", name: "Indeed" },
    { id: "104", name: "104 人力銀行" },
    { id: "cake", name: "CakeResume" },
    { id: "company", name: "公司官網" },
  ],
  industries: [
    { id: "tech.saas", name: "SaaS / B2B Software" },
    { id: "tech.consumer", name: "Consumer Tech" },
    { id: "fintech", name: "Fintech" },
    { id: "ai", name: "AI / Infra" },
    { id: "health", name: "Health Tech" },
    { id: "retail", name: "Retail / E-commerce" },
  ],
  jobs: [
    {
      id: "j_001", title: "Senior Product Manager, Growth",
      company: "Notion Labs", ticker: "—",
      country: "US", city: "San Francisco", remote: "hybrid",
      type: "Full-time", salaryMin: 180000, salaryMax: 230000, ccy: "USD",
      yearsMin: 5, yearsMax: 8, industry: "tech.saas",
      skills: ["Roadmap","Growth","Analytics","SQL"],
      postedAt: "2 天前", source: "greenhouse",
      sourceUrl: "https://boards.greenhouse.io/notion/jobs/example-12345",
      score: 0.91, matchReasons: ["Growth × Senior PM 對齊", "SaaS 經驗 5+ yr", "Roadmap 經驗"],
      desc: "Drive growth funnel for self-serve SaaS, partner with eng & marketing on activation experiments…",
    },
    {
      id: "j_002", title: "Product Manager, Platform",
      company: "Stripe", ticker: "—",
      country: "JP", city: "Tokyo", remote: "onsite",
      type: "Full-time", salaryMin: 16000000, salaryMax: 22000000, ccy: "JPY",
      yearsMin: 4, yearsMax: 7, industry: "fintech",
      skills: ["Platform","API","Stakeholder mgmt"],
      postedAt: "5 小時前", source: "lever",
      sourceUrl: "https://jobs.lever.co/stripe/example-pm-platform",
      score: 0.86, matchReasons: ["Stakeholder × API 經驗", "東京 location 偏好"],
      desc: "Own Stripe APIs roadmap for Japan market…",
    },
    {
      id: "j_003", title: "Senior PM, AI Copilot",
      company: "GitHub", ticker: "MSFT",
      country: "US", city: "Remote", remote: "remote",
      type: "Full-time", salaryMin: 195000, salaryMax: 245000, ccy: "USD",
      yearsMin: 6, yearsMax: 10, industry: "ai",
      skills: ["AI","Developer","Roadmap","Analytics"],
      postedAt: "1 天前", source: "linkedin",
      sourceUrl: "https://www.linkedin.com/jobs/view/example-3892",
      score: 0.84, matchReasons: ["AI 產品經驗", "Remote 偏好"],
      desc: "Define & ship Copilot Workspace for developers…",
    },
    {
      id: "j_004", title: "Product Manager, Consumer Growth",
      company: "Shopee", ticker: "SE",
      country: "TW", city: "Taipei", remote: "hybrid",
      type: "Full-time", salaryMin: 1800000, salaryMax: 2800000, ccy: "TWD",
      yearsMin: 4, yearsMax: 7, industry: "retail",
      skills: ["Growth","A/B Testing","Mobile"],
      postedAt: "3 天前", source: "104",
      sourceUrl: "https://www.104.com.tw/job/example-shopee",
      score: 0.79, matchReasons: ["Growth × A/B 對齊", "Taipei 在地"],
      desc: "Drive consumer activation for SE Asia marketplace…",
    },
    {
      id: "j_005", title: "Lead Product Manager, B2B SaaS",
      company: "Atlassian", ticker: "TEAM",
      country: "AU", city: "Sydney", remote: "hybrid",
      type: "Full-time", salaryMin: 230000, salaryMax: 290000, ccy: "AUD",
      yearsMin: 7, yearsMax: 12, industry: "tech.saas",
      skills: ["Roadmap","Stakeholder","Enterprise"],
      postedAt: "6 小時前", source: "lever",
      sourceUrl: "https://www.atlassian.com/company/careers/example-lead-pm",
      score: 0.74, matchReasons: ["B2B SaaS Senior PM"],
      desc: "Lead Jira Service Mgmt PM team…",
    },
    {
      id: "j_006", title: "Product Manager, Health Records",
      company: "Cake Health", ticker: "—",
      country: "TW", city: "Remote", remote: "remote",
      type: "Contract", salaryMin: 1500000, salaryMax: 2000000, ccy: "TWD",
      yearsMin: 3, yearsMax: 6, industry: "health",
      skills: ["FHIR","Compliance","Mobile"],
      postedAt: "12 小時前", source: "cake",
      sourceUrl: "https://www.cakeresume.com/jobs/example-cakehealth",
      score: 0.71, matchReasons: ["Mobile 經驗"],
      desc: "Build patient-facing health record app…",
    },
    {
      id: "j_007", title: "Senior PM, Payments",
      company: "Wise", ticker: "WISE.L",
      country: "GB", city: "London", remote: "hybrid",
      type: "Full-time", salaryMin: 95000, salaryMax: 130000, ccy: "GBP",
      yearsMin: 5, yearsMax: 9, industry: "fintech",
      skills: ["Payments","Compliance","API"],
      postedAt: "4 天前", source: "greenhouse",
      sourceUrl: "https://wise.jobs/example-senior-pm-payments",
      score: 0.69, matchReasons: ["Senior 年資"],
      desc: "Own cross-border payments roadmap…",
    },
    {
      id: "j_008", title: "Product Manager, Consumer AI",
      company: "Perplexity", ticker: "—",
      country: "US", city: "San Francisco", remote: "onsite",
      type: "Full-time", salaryMin: 200000, salaryMax: 260000, ccy: "USD",
      yearsMin: 4, yearsMax: 8, industry: "ai",
      skills: ["AI","Search","Mobile"],
      postedAt: "8 小時前", source: "company",
      sourceUrl: "https://www.perplexity.ai/careers/example-pm-consumer",
      score: 0.66, matchReasons: ["AI × Mobile"],
      desc: "Lead consumer answers experience…",
    },
  ],
  insightsByJob: {
    j_001: {
      swot: {
        S: ["5 年成長型 PM 經驗，與 JD growth 主軸對齊", "曾領導跨地區 A/B 實驗平台 build-out", "SQL × 數據文化匹配"],
        W: ["未直接帶過 enterprise self-serve 轉換漏斗", "主要工作經歷在亞洲，需強化美西 timezone 經驗論述"],
        O: ["Notion 正在擴張 SMB self-serve，履歷上的 PLG 案例可放大", "公司支援 hybrid，可遠端面試"],
        T: ["美西 PM 內推占比 ≥ 40%，建議拿 referral", "簽證:需要 H-1B sponsorship，公司近年較保守"],
      },
      risks: [
        { label: "工作授權", severity: "high", note: "JD 註明 must be authorized to work in the US." },
        { label: "competition", severity: "med", note: "頂級 SaaS 公司 senior PM 平均 200+ 申請者" },
      ],
      strategy:
        "三句話框架: (1) 你是 growth × international 雙能力 PM; (2) 5 年內推動過兩次 north-star metric 重構; (3) 想把這個能力帶到 Notion SMB self-serve。準備 STAR 案例聚焦 activation 漏斗 + 國際在地化。",
      questions: [
        { q: "How would you measure activation for Notion?", outline: "From signup → first workspace setup → 3-day retention. AAARRR layered metrics." },
        { q: "Walk me through a A/B test that surprised you.", outline: "Pick a story with clear hypothesis, unexpected result, follow-up causal analysis." },
        { q: "How to prioritize SMB vs enterprise roadmap?", outline: "RICE × strategic bets matrix. Discuss 80/20 + opportunistic enterprise wins." },
      ],
      refs: [
        { title: "Notion PM Interview Experience", source: "Glassdoor", url: "https://www.glassdoor.com/Interview/Notion-Labs-PM" },
        { title: "Senior PM expectations at SaaS scale-ups", source: "Lenny's Newsletter", url: "https://www.lennysnewsletter.com/example" },
        { title: "Notion product values", source: "Notion Blog", url: "https://www.notion.so/blog/values" },
      ],
    },
  },
  cvByJob: {
    j_001: {
      summary: { before: "Senior PM with experience in B2B SaaS.", after: "Senior Product Manager (6 yr), B2B SaaS growth specialist — drove activation +38% across two PLG products in Taipei × APAC." },
      bullets: [
        { before: "Led product roadmap for SaaS dashboard.", after: "Owned growth roadmap for B2B SaaS dashboard; ran 24 A/B tests in 12 months, lifting activation 38%." },
        { before: "Worked with engineering and marketing.", after: "Aligned eng / marketing / data on north-star metric; restructured weekly review to reduce roadmap churn 20%." },
        { before: "Used SQL to analyze user behavior.", after: "Self-serve SQL × Looker on warehouse; published a self-serve PM analytics handbook adopted org-wide." },
      ],
      diffNote: "全部改寫均基於原履歷既有事實,僅重新框架與量化。",
    },
  },
  industries: [
    { id: "tech.saas", name: "SaaS / B2B Software" },
    { id: "tech.consumer", name: "Consumer Tech" },
    { id: "fintech", name: "Fintech" },
    { id: "ai", name: "AI / Infra" },
    { id: "health", name: "Health Tech" },
    { id: "retail", name: "Retail / E-commerce" },
  ],
  top100Sample: {
    "tech.saas": [
      { rank: 1, name: "Microsoft", ticker: "MSFT", price: 432.10, d1: 0.011, m1: 0.063, y1: 0.21,
        pros: ["穩定 / 福利優","WLB 中等","內部移動容易"], cons: ["大公司流程","升遷慢"],
        profile: "綜合 SaaS + 雲 + AI Copilot 旗艦", trend: "AI Copilot 商業化加速,Azure 持續成長",
        sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/" }, { name: "10-K", url: "https://www.microsoft.com/investor" }] },
      { rank: 2, name: "Salesforce", ticker: "CRM", price: 271.55, d1: -0.004, m1: 0.022, y1: 0.09,
        pros: ["Trailhead 學習文化","國際機會多"], cons: ["年度評估壓力大","RTO 政策爭議"],
        profile: "CRM + Data Cloud + AI Agentforce", trend: "Agentforce 帶動 attach,但成熟期競爭加劇",
        sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/" }] },
      { rank: 3, name: "Atlassian", ticker: "TEAM", price: 210.30, d1: 0.018, m1: 0.041, y1: 0.18,
        pros: ["遠距文化成熟","明確 OKR"], cons: ["澳洲 vs 美國時差","新鮮人路徑少"],
        profile: "Jira / Confluence / Loom", trend: "Cloud 遷移已過半,Rovo AI 為下一動能",
        sources: [{ name: "Atlassian Blog", url: "https://www.atlassian.com/blog" }] },
      { rank: 4, name: "ServiceNow", ticker: "NOW", price: 988.20, d1: 0.007, m1: 0.038, y1: 0.27,
        pros: ["企業客戶穩","學習曲線陡"], cons: ["產品線複雜","內部政治"],
        profile: "Workflow 平台龍頭", trend: "AI agent 整合 + 政府市場擴張",
        sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/" }] },
      { rank: 5, name: "Notion Labs", ticker: "—", price: null, d1: null, m1: null, y1: null,
        pros: ["設計文化強","產品 craft 高"], cons: ["fast pace","SF 為主"],
        profile: "Workspace × AI", trend: "Q&A / Agent 推動 ARPU 成長",
        sources: [{ name: "Notion Careers", url: "https://www.notion.so/careers" }] },
      { rank: 6, name: "HubSpot", ticker: "HUBS", price: 605.10, d1: 0.005, m1: 0.013, y1: 0.10,
        pros: ["WLB 良好","社群文化"], cons: ["漲薪 cap","產品線割裂"],
        profile: "SMB CRM × Marketing", trend: "AI 助理 Breeze 補強 stack",
        sources: [{ name: "Glassdoor", url: "https://www.glassdoor.com/" }] },
    ],
    "ai": [
      { rank: 1, name: "OpenAI", ticker: "—", price: null, pros: ["前沿研究","資源充沛"], cons: ["人事波動大","壓力高"], profile: "通用 AI 旗艦", trend: "GPT-5 推進 enterprise + agent 能力", sources: [] },
      { rank: 2, name: "Anthropic", ticker: "—", price: null, pros: ["安全研究強","研究氛圍"], cons: ["招聘 bar 極高","產品線少"], profile: "Claude × 安全", trend: "Enterprise 客戶快速成長", sources: [] },
      { rank: 3, name: "Nvidia", ticker: "NVDA", price: 1080, d1: 0.022, m1: 0.18, y1: 0.92, pros: ["薪酬頂級","CUDA 護城河"], cons: ["強度高","硬體限制"], profile: "AI 算力 + 軟體生態", trend: "Blackwell 推進 + 自有 cloud", sources: [] },
      { rank: 4, name: "Perplexity", ticker: "—", price: null, pros: ["快速迭代","產品 craft"], cons: ["商業模式仍試錯","資金壓力"], profile: "搜尋 × 答覆", trend: "進攻 enterprise search", sources: [] },
    ],
    "fintech": [
      { rank: 1, name: "Visa", ticker: "V", price: 285.20, d1: 0.003, m1: 0.018, y1: 0.12, pros: ["穩定","全球機會"], cons: ["大公司步調","創新慢"], profile: "卡組織龍頭", trend: "real-time payment + token 業務", sources: [] },
      { rank: 2, name: "Stripe", ticker: "—", price: null, pros: ["工程文化","國際視野"], cons: ["升遷 bar 高","RTO"], profile: "Internet 經濟基礎建設", trend: "AI agent payments + capital 業務", sources: [] },
      { rank: 3, name: "Wise", ticker: "WISE.L", price: 8.20, d1: 0.005, m1: 0.012, y1: 0.04, pros: ["透明文化","遠距彈性"], cons: ["薪資較其他金融低","成長 plateau"], profile: "跨境匯款", trend: "B2B & 平台合作擴張", sources: [] },
    ],
  },
};
